Algoritmo "crescente"


Var
  x, y : inteiro

Inicio

      escreval("Digite dois números:")
      leia(x)
      leia(y)
      
      enquanto x <> y faca

         se x < y entao
            escreval("Crescente")
         senao
            escreval("Degrescente")
         fimse


           
         "Digite outros dois números")
         leia(x)
         Leia(y)
         
     fimenquanto
Fimalgoritmo
