Algoritmo "senha_fixa"




Var

   senha, tentativa : inteiro


Inicio

      senha <- 2002
 

      escreva("Insira uma senha com 4 digito.")
      leia(tentativa)
      
      enquanto tentativa <> senha faca
         escreva("Senha Invalida! Tente novemente: ")
            leia(tentativa)
         
      fimenquanto
      
      se tentativa = senha entao
         escreval("Acesso Permitido")
         
         fimse

            


      




Fimalgoritmo